Repository Pullanner/pullanner-web, pull requests merged in 2023-06, with the labels that each got.

#5 Feature/#2 login 인증 과정
  .env
  index.html
  public/assets/google-icon.svg
  public/assets/kakao-icon.svg
  public/assets/logo.svg
  public/assets/naver-icon.svg
  src/App.tsx
  src/components/LoginButton/index.tsx
  src/pages/ErrorPage/index.tsx
  src/pages/Login/index.tsx
  src/pages/LoginLoading/index.tsx
  src/pages/Root/index.tsx
  src/pages/index.tsx
  src/stores/accessTokenAtom.ts
  src/utils/cookie.ts
  tailwind.config.cjs
Labels: ✨ Feature

#4 [Deploy] React App 자동 빌드 및 배포 환경 구축
  .github/workflows/cicd-fe.yml
  .github/workflows/manual-deploy-fe.yml
Labels: 🌏 Deploy

#12 Feature/#7 login authorization
  src/lib/axios/authInstance.ts
  src/lib/axios/defaultInstance.ts
Labels: ✨ Feature

#17 Refactor/#13 login authorization
  src/hooks/useAuthApi.ts
  src/lib/axios/authInstance.ts
  src/pages/LoginLoading/index.tsx
  src/stores/atoms/accessTokenAtom.ts
  src/utils/reissueAccessToken.ts
Labels: 🔨 Refactor

#18 Feature/#15 header
  public/assets/back-button.svg
  public/assets/user-icon.svg
  src/components/Header/index.tsx
  src/components/LoginButton/index.tsx
  src/hooks/usePreviuosPage.ts
  src/pages/Login/index.tsx
  src/pages/LoginLoading/index.tsx
  src/pages/Root/index.tsx
  src/stores/atoms/loginStateAtom.ts
Labels: ✨ Feature

#19 Feature/#16 bottom navigation bar
  index.html
  public/assets/fonts/icomoon.eot
  public/assets/fonts/icomoon.svg
  public/assets/fonts/icomoon.ttf
  public/assets/fonts/icomoon.woff
  public/assets/fontstyle.css
  public/assets/images/back-button.svg
  public/assets/images/community-icon.svg
  public/assets/images/dashboard-icon.svg
  public/assets/images/google-icon.svg
  public/assets/images/journal-icon.svg
  public/assets/images/kakao-icon.svg
  public/assets/images/logo.svg
  public/assets/images/naver-icon.svg
  public/assets/images/roadmap-icon.svg
  public/assets/images/user-icon.svg
  src/components/BottomNavigationBar/index.tsx
  src/components/Header/index.tsx
  src/components/LoginButton/index.tsx
  src/hooks/usePreviuosPage.ts
  src/pages/Login/index.tsx
  src/pages/Root/index.tsx
Labels: 🔨 Refactor, ✨ Feature

#23 Refactor/#20 configs login logic
  .eslintrc.cjs
  src/components/BottomNavigationBar/index.tsx
  src/components/Header/index.tsx
  src/components/LoginButton/index.tsx
  src/constants/index.ts
  src/constants/routePath.ts
  src/lib/axios/authInstance.ts
  src/lib/axios/defaultInstance.ts
  src/pages/Login/index.tsx
  src/pages/LoginLoading/index.tsx
  src/pages/Root/index.tsx
  src/utils/reissueAccessToken.ts
  tailwind.config.cjs
Labels: 🔨 Refactor

#24 Feature/#22 my page
  public/assets/images/edit-icon.svg
  src/App.tsx
  src/components/BottomNavigationBar/index.tsx
  src/components/Header/index.tsx
  src/components/LargeBlockButton/index.tsx
  src/components/LoginButton/index.tsx
  src/components/MyPage/ProgressSection/index.tsx
  src/components/MyPage/TabSecion/index.tsx
  src/components/MyPage/UserSection/index.tsx
  src/components/MyPage/index.tsx
  src/components/Tabs/index.tsx
  src/constants/apiPath.ts
  src/constants/index.ts
  src/constants/routePath.ts
  src/index.css
  src/lib/axios/useAuthApi.ts
  src/lib/react-query/queryKeys.ts
  src/lib/react-query/useUserData.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/user/data.ts
  src/mocks/user/handler.ts
  src/pages/Login/index.tsx
  src/pages/LoginLoading/index.tsx
  src/pages/MyPage/constants.ts
  src/pages/MyPage/index.tsx
  src/pages/index.tsx
  src/utils/reissueAccessToken.ts
  tailwind.config.cjs
Labels: 🔨 Refactor, ✨ Feature

#27 Refactor/#26 my page
  src/App.tsx
  src/components/MyPage/ProgressSection/index.tsx
  src/components/MyPage/TabSection/index.tsx
  src/components/MyPage/index.tsx
  src/constants/index.ts
  src/constants/maxJournalCountByLevel.ts
  src/lib/axios/useAuthApi.ts
  src/lib/react-query/useUserData.ts
  src/mocks/user/data.ts
  src/pages/MyPage/index.tsx
  src/utils/percent.ts
Labels: 🔨 Refactor

#29 Refactor/#26 my page
  src/components/MyPage/ProgressSection/index.tsx
  src/components/ProgressBar/index.tsx
  src/utils/percent.ts
Labels: 🔨 Refactor

#31 Refactor/#30 jotai
  .yarn/cache/hamt_plus-npm-1.0.2-67a52ee1df-af26ea32db.zip
  .yarn/cache/jotai-npm-2.2.1-f4327ead2c-1400d03205.zip
  .yarn/cache/recoil-npm-0.7.6-6f8de04e3d-2b31dd29a7.zip
  package.json
  src/App.tsx
  src/components/Header/index.tsx
  src/hooks/usePreviousPage.ts
  src/pages/LoginLoading/index.tsx
  src/pages/MyPage/index.tsx
  src/stores/atoms/accessTokenAtom.ts
  src/stores/atoms/loginStateAtom.ts
  yarn.lock
Labels: 🔨 Refactor

#33 Refactor/#32 UI
  src/App.tsx
  src/components/BottomNavigationBar/index.tsx
  src/components/DimmedButton/index.tsx
  src/components/LargeBlockButton/index.tsx
  src/components/MyPage/ProgressSection/index.tsx
  src/components/MyPage/TabSection/index.tsx
  src/components/MyPage/UserSection/index.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/Root/index.tsx
  tailwind.config.cjs
Labels: 🔨 Refactor, 🎨 Design
