Repository Pullanner/pullanner-web, pull requests merged in 2023-07, with the labels that each got.

#38 Feat/#9 roadmap
  public/assets/images/roadmap-banner.svg
  public/assets/images/roadmap/step1.svg
  public/assets/images/roadmap/step2.svg
  public/assets/images/roadmap/step3.svg
  public/assets/images/roadmap/step4.svg
  public/assets/images/roadmap/step5.svg
  public/assets/images/roadmap/step6.svg
  public/assets/images/roadmap/step7.svg
  public/assets/images/roadmap/step8.svg
  src/App.tsx
  src/components/Banner/index.tsx
  src/components/BottomNavigationBar/index.tsx
  src/components/Header/index.tsx
  src/components/Rate/index.tsx
  src/constants/bannerText.ts
  src/constants/roadmapData.ts
  src/constants/routePath.ts
  src/index.css
  src/pages/Roadmap/RoadmapCard.tsx
  src/pages/Roadmap/index.tsx
  src/pages/RoadmapDetail/RoadmapNav.tsx
  src/pages/RoadmapDetail/index.tsx
  src/pages/Root/index.tsx
  src/pages/index.tsx
  yarn.lock
Labels: 🎨 Design, ✨ Feature

#41 [#37] Feat: implement and apply scroll top button component
  public/assets/images/up-arrow.png
  src/components/ScrollTopButton/index.tsx
  src/pages/Root/index.tsx
Labels: ✨ Feature

#43 Feat/#21 edit my page
  .yarn/cache/@esbuild-win32-x64-npm-0.17.19-619fae7839-8.zip
  src/App.tsx
  src/apis/user/getUserData.ts
  src/apis/user/index.ts
  src/apis/user/postUserData.ts
  src/apis/user/validateNickname.ts
  src/components/DuplicationCheckForm/InputDescription.tsx
  src/components/DuplicationCheckForm/constants.ts
  src/components/DuplicationCheckForm/index.tsx
  src/components/Header/index.tsx
  src/components/LoginButton/index.tsx
  src/components/ProfileImage/index.tsx
  src/components/SaveButton/index.tsx
  src/constants/apiPath.ts
  src/constants/index.ts
  src/lib/react-query/useUserData.ts
  src/mocks/user/data.ts
  src/mocks/user/handler.ts
  src/pages/EditMyPage/index.tsx
  src/pages/MyPage/TabSection.tsx
  src/pages/MyPage/UserSection.tsx
  src/pages/MyPage/index.tsx
  src/pages/Roadmap/index.tsx
  src/pages/RoadmapDetail/RoadmapNav.tsx
  src/pages/RoadmapDetail/index.tsx
  src/pages/index.tsx
  src/utils/reissueAccessToken.ts
Labels: 🔨 Refactor, ✨ Feature

#50 Deploy/#46 edit my page
  src/apis/user/getUserData.ts
  src/apis/user/getUserDataTest.ts
  src/apis/user/index.ts
  src/apis/user/postUserDataTest.ts
  src/apis/user/validateNickname.ts
  src/lib/axios/useAuthApi.ts
  src/lib/react-query/useUserData.ts
Labels: 🌏 Deploy

#52 [#51] Feat: redirect to roadmap page on root path
  src/App.tsx
  src/pages/Root/rootLoader.ts
  src/pages/index.tsx
Labels: ✨ Feature

#54 [#53] Refactor: modify redirect logic by using useNavigate
  src/pages/LoginLoading/index.tsx
Labels: 🔨 Refactor

#56 Refactor/#55 modify domain url
  .env
  index.html
Labels: 🔨 Refactor, ✨ Feature

#58 Feat/#47 modal
  index.html
  src/components/Modal/ModalButton.tsx
  src/components/Modal/ModalText.tsx
  src/components/Modal/index.tsx
  src/constants/routePath.ts
  src/pages/EditMyPage/index.tsx
Labels: ✨ Feature

#66 Refactor/#62 my page
  src/components/DuplicationCheckInput/InputDescription.tsx
  src/components/DuplicationCheckInput/constants.ts
  src/components/DuplicationCheckInput/index.tsx
  src/components/buttons/SaveButton/index.tsx
  src/lib/react-query/useUserData.ts
  src/mocks/user/data.ts
  src/pages/EditMyPage/index.tsx
  src/pages/MyPage/UserSection.tsx
  src/pages/MyPage/index.tsx
  src/pages/Root/index.tsx
  src/stores/atoms/userDataAtom.ts
  src/utils/initializeAccessToken.ts
Labels: 🔨 Refactor, ✨ Feature

#68 Feat/#63 plan
  public/assets/images/banner/plan.png
  src/App.tsx
  src/apis/plans/getPlans.ts
  src/components/BottomNavigationBar/index.tsx
  src/constants/apiPath.ts
  src/constants/bannerData.ts
  src/constants/routePath.ts
  src/index.css
  src/lib/react-query/queryKeys.ts
  src/lib/react-query/useGetPlan.ts
  src/mocks/handlers.ts
  src/mocks/plans/data.ts
  src/mocks/plans/handler.ts
  src/pages/Journal/JournalCard.tsx
  src/pages/Journal/index.tsx
  src/pages/Journal/mockData.ts
  src/pages/Plan/PlanButtons/index.tsx
  src/pages/Plan/PlanCalendar/CalendarCell.tsx
  src/pages/Plan/PlanCalendar/CalendarHeader.tsx
  src/pages/Plan/PlanCalendar/customColorToken.ts
  src/pages/Plan/PlanCalendar/index.tsx
  src/pages/Plan/PlanCard/index.tsx
  src/pages/Plan/index.tsx
  src/pages/Root/index.tsx
  src/pages/index.tsx
  src/types/plan.ts
Labels: 🔨 Refactor, 🎨 Design, ✨ Feature

#69 Deploy/#67 api
  src/apis/user/getUserDataTest.ts
  src/apis/user/index.ts
  src/apis/user/postUserDataTest.ts
  src/apis/user/validateNickname.ts
  src/components/DuplicationCheckInput/index.tsx
  src/lib/axios/authInstance.ts
  src/lib/axios/instance.ts
  src/lib/axios/useAuthApi.ts
  src/lib/react-query/useUserData.ts
  src/pages/EditMyPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/Plan/PlanCalendar/CalendarHeader.tsx
  src/stores/atoms/accessTokenAtom.ts
  src/utils/reissueAccessToken.ts
Labels: 🔨 Refactor
